DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS goal;
CREATE TABLE goal (
   ID INTEGER PRIMARY KEY    AUTOINCREMENT,
   GOAL           TEXT    NOT NULL,
   TIME_COMMITMENT            INT     NOT NULL,
   LOGGING        CHAR(50),
   USERID   INT

);
CREATE TABLE user (
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   EMAIL            TEXT     NOT NULL
);
INTO goal (GOAL, TIME_COMMITMENT, LOGGING ) VALUES (1, 'IT Billing', 1 );
